plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.google.android.libraries.mapsplatform.secrets.gradle.plugin)
    alias(libs.plugins.androidx.navigation.safeargs)
}

android {
    namespace 'com.kimikevin.eatsplorer'
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        applicationId "com.kimikevin.eatsplorer"
        minSdk 24
        targetSdk 37
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        Properties properties = new Properties()
        if (rootProject.file('local.properties').exists()) {
            properties.load(rootProject.file('local.properties').newDataInputStream())
        }

        manifestPlaceholders["googleMapsApiKey"] = properties.getProperty('GMP_KEY', "")
        buildConfigField "String", "GOOGLE_MAPS_API_KEY", "\"${properties.getProperty('GMP_KEY', "")}\""
    }

    buildTypes {
        release {
            optimization {
                enable false
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        viewBinding true
        buildConfig true
    }
}

dependencies {
    // room
    def room_version = "2.7.2"

    implementation "androidx.room:room-runtime:$room_version"
    annotationProcessor "androidx.room:room-compiler:$room_version"

    implementation libs.activity
    implementation libs.appcompat
    implementation libs.constraintlayout
    implementation libs.material

    // AndroidX
    implementation libs.androidx.core
    implementation libs.androidx.core.splashscreen
    implementation libs.androidx.lifecycle.viewmodel
    implementation libs.androidx.navigation.fragment
    implementation libs.androidx.navigation.ui
    implementation libs.androidx.viewpager2

    // Networking
    implementation libs.retrofit
    implementation libs.converter.gson
    implementation libs.logging.interceptor

    // Image Loading
    implementation libs.glide
    annotationProcessor libs.glide.compiler

    // UI Components
    implementation libs.dotsindicator

    // Google Play Services
    implementation libs.play.services.location
    implementation libs.play.services.maps
    implementation libs.places

    testImplementation libs.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ext.junit
}
